In [1]:
import os
import sys
sys.path.insert(0, os.path.abspath('../src'))

In [6]:
import pandas as pd
from sklearn import preprocessing

In [3]:
import categorical

In [7]:
df = pd.read_csv("../input/train_cat.csv")

In [8]:
lbl = preprocessing.

id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2       nom_3  \
0   0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster      Russia   
1   1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl         NaN   
2   2    0.0    1.0    0.0     F     N   Red        NaN  Hamster      Canada   
3   3    NaN    0.0    0.0     F     N   Red     Circle  Hamster     Finland   
4   4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster  Costa Rica   
5   5    0.0    NaN    1.0     T     N   Red   Triangle     Lion       China   
6   6    0.0    0.0    0.0     F     N   Red   Triangle  Hamster  Costa Rica   
7   7    0.0    0.0    1.0     T     N   Red   Triangle  Axolotl     Finland   
8   8    0.0    0.0    0.0     F     N  Blue    Polygon  Hamster      Russia   
9   9    0.0    0.0    NaN     F     Y   Red    Polygon  Hamster     Finland   

   ...      nom_9 ord_0        ord_1        ord_2 ord_3 ord_4  ord_5  day  \
0  ...  02e7c8990   3.0  Contributor          Hot     c     U     Pw  6.0   
1  ...  f37df64af   3.0  Grandmaster         Warm     e     X     pE  7.0   
2  ...        NaN   3.0          NaN     Freezing     n     P     eN  5.0   
3  ...  f9d456e57   1.0       Novice     Lava Hot     a     C    NaN  3.0   
4  ...  c5361037c   3.0  Grandmaster         Cold     h     C     OZ  5.0   
5  ...  05afc0f8b   2.0       Expert          Hot     b     Q     wa  3.0   
6  ...  4d3766412   1.0  Grandmaster         Cold     c     R     rg  5.0   
7  ...  a651dec43   3.0       Expert         Cold     b     Y     PS  1.0   
8  ...        NaN   1.0       Novice  Boiling Hot     c     N     mX  6.0   
9  ...  79b29d54c   3.0  Contributor     Lava Hot     n     I     OZ  1.0   

  month target  
0   3.0      0  
1   7.0      0  
2   9.0      0  
3   3.0      0  
4  12.0      0  
5   4.0      0  
6   6.0      0  
7   1.0      0  
8   3.0      0  
9   8.0      1  

[10 rows x 25 columns]

In [4]:
df.columns


Index(['id', 'bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'nom_0', 'nom_1',
       'nom_2', 'nom_3', 'nom_4', 'nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9',
       'ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4', 'ord_5', 'day', 'month',
       'target'],
      dtype='object')

In [5]:
df["target"]

0         0
1         0
2         0
3         0
4         0
         ..
599995    0
599996    0
599997    0
599998    0
599999    0
Name: target, Length: 600000, dtype: int64

In [6]:
df.target.value_counts


<bound method IndexOpsMixin.value_counts of 0         0
1         0
2         0
3         0
4         0
         ..
599995    0
599996    0
599997    0
599998    0
599999    0
Name: target, Length: 600000, dtype: int64>

In [7]:
df.target.value_counts()

0    487677
1    112323
Name: target, dtype: int64

In [6]:
df

id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2  \
0            0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster   
1            1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl   
2            2    0.0    1.0    0.0     F     N   Red        NaN  Hamster   
3            3    NaN    0.0    0.0     F     N   Red     Circle  Hamster   
4            4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster   
...        ...    ...    ...    ...   ...   ...   ...        ...      ...   
599995  599995    0.0    1.0    0.0     T     N   Red    Polygon  Axolotl   
599996  599996    1.0    0.0    0.0     T     Y  Blue    Polygon      Dog   
599997  599997    0.0    0.0    0.0     F     Y   Red     Circle  Axolotl   
599998  599998    1.0    1.0    0.0     F     Y   NaN    Polygon  Axolotl   
599999  599999    0.0    0.0    0.0     T     N  Blue   Triangle      Dog   

             nom_3  ...      nom_9 ord_0        ord_1        ord_2 ord_3  \
0           Russia  ...  02e7c8990   3.0  Contributor          Hot     c   
1              NaN  ...  f37df64af   3.0  Grandmaster         Warm     e   
2           Canada  ...        NaN   3.0          NaN     Freezing     n   
3          Finland  ...  f9d456e57   1.0       Novice     Lava Hot     a   
4       Costa Rica  ...  c5361037c   3.0  Grandmaster         Cold     h   
...            ...  ...        ...   ...          ...          ...   ...   
599995       India  ...  015c63324   3.0       Novice     Freezing     a   
599996  Costa Rica  ...  a02ae6a63   2.0       Novice  Boiling Hot     n   
599997      Russia  ...  40f9610c1   2.0  Contributor     Freezing     n   
599998         NaN  ...  c1a8374a0   1.0       Master         Warm     m   
599999      Russia  ...  e2aea7784   1.0  Contributor  Boiling Hot     b   

       ord_4  ord_5  day month target  
0          U     Pw  6.0   3.0      0  
1          X     pE  7.0   7.0      0  
2          P     eN  5.0   9.0      0  
3          C    NaN  3.0   3.0      0  
4          C     OZ  5.0  12.0      0  
...      ...    ...  ...   ...    ...  
599995     R     GZ  5.0   NaN      0  
599996     N     sf  NaN   3.0      0  
599997     H     MV  7.0   5.0      0  
599998     X     Ey  1.0   5.0      0  
599999     O     uI  5.0   8.0      0  

[600000 rows x 25 columns]

In [8]:
df.bin_4.value_counts()

N    312344
Y    269609
Name: bin_4, dtype: int64

In [9]:
df.nom_0.value_counts()

Red      323286
Blue     205861
Green     52601
Name: nom_0, dtype: int64

In [11]:
df.ord_2.values

array(['Hot', 'Warm', 'Freezing', ..., 'Freezing', 'Warm', 'Boiling Hot'],
      dtype=object)

In [12]:
df.day.values


array([6., 7., 5., ..., 7., 1., 5.])

In [23]:

df.month.value_counts()

8.0     79245
3.0     70160
5.0     68906
12.0    68340
6.0     60478
7.0     53480
1.0     52154
11.0    51165
2.0     40700
9.0     20620
4.0     14614
10.0     2150
Name: month, dtype: int64

In [13]:
df.target.value_counts()

0    487677
1    112323
Name: target, dtype: int64

In [15]:
lbl = preprocessing.OneHotEncoder()
lbl.fit(df[["bin_0", "bin_1"]].fillna(-1).values)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [16]:
lbl.transform(df[["bin_0", "bin_1"]].fillna(-1))

<600000x6 sparse matrix of type '<class 'numpy.float64'>'
	with 1200000 stored elements in Compressed Sparse Row format>

In [24]:
df_sample = pd.read_csv("../input/sample_cat_submission.csv")

In [22]:
df_sample

id  target
0  600000     0.5
1  600001     0.5
2  600002     0.5
3  600003     0.5
4  600004     0.5

In [20]:
import sys
sys.path.append('../src/')

In [8]:
import pandas as pd
from sklearn import linear_model
df = pd.read_csv("../input/train_cat.csv")
df_test = pd.read_csv("../input/test_cat.csv")
sample = pd.read_csv("../input/sample_submission.csv")


train_len = len(df)

df_test["target"] = -1
full_data = pd.concat([df, df_test])

cols = [c for c in df.columns if c not in ["id", "target"]]
print(cols)
cat_feats = categorical.CategoricalFeatures(full_data, 
                                    categorical_features=cols, 
                                    encoding_type="ohe",
                                    handle_na=True)
full_data_transformed = cat_feats.fit_transform()
    
X = full_data_transformed[:train_len, :]
X_test = full_data_transformed[train_len:, :]

clf = linear_model.LogisticRegression()
clf.fit(X, df.target.values)
preds = clf.predict_proba(X_test)[:, 1]
    
sample.loc[:, "target"] = preds
sample.to_csv("submission2.csv", index=False)

['bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'nom_0', 'nom_1', 'nom_2', 'nom_3', 'nom_4', 'nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9', 'ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4', 'ord_5', 'day', 'month']


/home/abisheksrivastav/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [9]:
print(sample.loc[:, "target"] )

0         0.086338
1         0.251306
2         0.147183
3         0.107830
4         0.096754
            ...   
399995    0.595217
399996    0.443251
399997    0.580236
399998    0.248858
399999    0.177401
Name: target, Length: 400000, dtype: float64


In [10]:
print(sample)

            id    target
0       600000  0.086338
1       600001  0.251306
2       600002  0.147183
3       600003  0.107830
4       600004  0.096754
...        ...       ...
399995  999995  0.595217
399996  999996  0.443251
399997  999997  0.580236
399998  999998  0.248858
399999  999999  0.177401

[400000 rows x 2 columns]


In [11]:
print(preds)

[0.08633787 0.25130609 0.14718259 ... 0.5802355  0.24885834 0.17740122]


In [15]:
s= sample.loc[:, "target"] = preds

In [16]:
print(s)

[0.08633787 0.25130609 0.14718259 ... 0.5802355  0.24885834 0.17740122]
